"use client";
import { useEffect, useRef, useState } from 'react';
import { ArrowUp, RefreshCw, Bookmark, Download } from 'lucide-react';
import { Sidebar, SidebarContent, SidebarFooter, SidebarHeader, SidebarInset, SidebarProvider, SidebarTrigger } from '@/components/ui/sidebar';
import { Button } from '@/components/ui/button';
import { Textarea } from '@/components/ui/textarea';
import { Sheet, SheetContent, SheetDescription, SheetHeader, SheetTitle } from '@/components/ui/sheet';
import type { ResearchView, SavedAnalysis } from '@/lib/research-types';
import type { MarketSnapshot } from '@/lib/market';

const date=(value:string)=>new Date(value).toLocaleString(undefined,{dateStyle:'medium',timeStyle:'short'});
const percent=(value:number)=>`${value>=0?'+':''}${value.toFixed(2)}%`;
export default function ReviewApp(){
 const [ticker,setTicker]=useState('');const [data,setData]=useState<ResearchView|null>(null);
 const [recent,setRecent]=useState<string[]>([]);const [configured,setConfigured]=useState(false);
 const [auth,setAuth]=useState(false);const [loading,setLoading]=useState(false);const [busy,setBusy]=useState(false);
 const [error,setError]=useState('');const [status,setStatus]=useState('');const [question,setQuestion]=useState('');
 const [selectedExcerpt,setSelectedExcerpt]=useState('');const [excerptOwner,setExcerptOwner]=useState('');
 const [alternative,setAlternative]=useState('');const [compareDate,setCompareDate]=useState('');const [researchConfigured,setResearchConfigured]=useState(false);
 const [noteOpen,setNoteOpen]=useState(false);const [note,setNote]=useState('');const [noteBusy,setNoteBusy]=useState(false);
 const [info,setInfo]=useState(false);const sequence=useRef(0);const aiBusy=useRef(false);
 useEffect(()=>{
  fetch('/api/chat').then(r=>r.json()).then(body=>{const setup=body as {configured?:boolean;researchConfigured?:boolean};setConfigured(setup.configured===true);setResearchConfigured(setup.researchConfigured===true);}).catch(()=>{});
  try{const saved=JSON.parse(localStorage.getItem('hindsight-real-stocks')||'[]');if(Array.isArray(saved)){const valid=saved.filter(s=>typeof s==='string'&&/^[A-Z0-9][A-Z0-9.^=-]{0,19}$/.test(s)).slice(0,10);setRecent(valid);if(valid[0])void openStock(valid[0]);}}catch{}
 },[]);
 async function openStock(symbol:string,refresh=false){
  const current=++sequence.current;const normalized=symbol.trim().toUpperCase();
  if(!/^[A-Z0-9][A-Z0-9.^=-]{0,19}$/.test(normalized)){setError('Enter a ticker, such as AAPL or SHOP.TO.');return;}
  setLoading(true);setError('');setStatus('');setTicker(normalized);setData(null);setQuestion('');setNoteOpen(false);setSelectedExcerpt('');setExcerptOwner('');
  try{
   const response=await fetch(`/api/research?symbol=${encodeURIComponent(normalized)}${refresh?'&refresh=1':''}`);
   const body=await response.json() as ResearchView&{error?:string};
   if(current!==sequence.current)return;
   if(!response.ok){if(response.status===401)setAuth(true);throw new Error(body.error||'Could not load this stock.');}
   setAuth(false);setData(body);
   setRecent(previous=>{const next=[normalized,...previous.filter(s=>s!==normalized)].slice(0,10);try{localStorage.setItem('hindsight-real-stocks',JSON.stringify(next));}catch{}return next;});
  }catch(e){if(current===sequence.current)setError((e as Error).message);}
  finally{if(current===sequence.current)setLoading(false);}
 }
 async function ask(kind:'catchup'|'question',text=question){
  if(!data||aiBusy.current||(!text.trim()&&kind==='question'))return;
  const current=sequence.current;const symbol=data.market.symbol;
  aiBusy.current=true;setBusy(true);setError('');setStatus('');
  try{
   const response=await fetch('/api/chat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({symbol,kind,question:kind==='question'?text:undefined,fetchedAt:data.market.fetchedAt})});
   const body=await response.json() as {analysis:SavedAnalysis;cached:boolean;error?:string};
   if(current!==sequence.current)return;
   if(!response.ok){if(response.status===401)setAuth(true);throw new Error(body.error||'Could not answer. Please retry.');}
   setData(previous=>previous?{...previous,analyses:[body.analysis,...previous.analyses.filter(a=>a.id!==body.analysis.id)].slice(0,30)}:previous);
   setQuestion(previous=>previous===text?'':previous);setStatus(body.cached?'Reused your saved catch-up. No AI call needed.':'Analysis saved with its sources.');
  }catch(e){if(current===sequence.current)setError((e as Error).message);}
  finally{aiBusy.current=false;setBusy(false);}
 }
 function remember(text=''){setNote(text.slice(0,600));setNoteOpen(true);}
 async function saveNote(){
  if(!data||!note.trim()||noteBusy)return;const current=sequence.current;setNoteBusy(true);setError('');
  try{const response=await fetch('/api/notes',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({symbol:data.market.symbol,text:note})});const body=await response.json() as {note:ResearchView['notes'][number];error?:string};if(!response.ok)throw new Error(body.error||'Could not save note.');if(current===sequence.current){setData(prev=>prev?{...prev,notes:[body.note,...prev.notes]}:prev);setNoteOpen(false);setStatus('Note saved. It will be included in future AI answers for this stock.');}}catch(e){setError((e as Error).message);}finally{setNoteBusy(false);}
 }
 async function removeNote(id:string){const current=sequence.current;try{const r=await fetch(`/api/notes?id=${encodeURIComponent(id)}`,{method:'DELETE'});if(!r.ok)throw new Error('Could not remove note.');if(current===sequence.current)setData(prev=>prev?{...prev,notes:prev.notes.filter(n=>n.id!==id)}:prev);}catch(e){setError((e as Error).message);}}
 const latest=data?.analyses.find(a=>a.kind==='catchup');
 const previous=data?.analyses.filter(a=>a.kind==='catchup'&&a.id!==latest?.id)??[];
 const followups=data?.analyses.filter(a=>a.kind==='question').slice(0,8).reverse()??[];
 return <SidebarProvider defaultOpen={false}><Sidebar className="app-sidebar"><SidebarHeader><a className="brand" href="/">hindsight.</a></SidebarHeader><SidebarContent><p className="sidebar-label">RECENT STOCKS</p>{recent.length?recent.map(symbol=><button className={`stock-nav ${data?.market.symbol===symbol?'selected':''}`} key={symbol} onClick={()=>void openStock(symbol)}><strong>{symbol}</strong><span>Open saved research</span></button>):<p className="small muted">Your stocks will appear here.</p>}</SidebarContent><SidebarFooter><button className="small muted" onClick={()=>setInfo(true)}>Sources & setup</button></SidebarFooter></Sidebar>
 <SidebarInset className="app-main"><header className="topbar"><div className="brand-row"><SidebarTrigger/><a href="/">hindsight<span>.</span></a></div><button className="sample-badge" onClick={()=>setInfo(true)}>{configured?(researchConfigured?'Research ready':'DeepSeek configured'):'DeepSeek key needed'}</button></header>
 <main className="conversation-workspace"><form className="ticker-form" onSubmit={e=>{e.preventDefault();void openStock(ticker);}}><label htmlFor="ticker">Your stock</label><div><input id="ticker" value={ticker} onChange={e=>setTicker(e.target.value)} placeholder="Ticker, e.g. AAPL or SHOP.TO" maxLength={20} autoComplete="off" spellCheck={false}/><Button disabled={loading||!ticker.trim()} type="submit">{loading?'Loading…':'Open stock'}</Button></div></form>
 {error&&<div className="notice" role="alert">{error}{auth&&<a href="/signin-with-chatgpt?return_to=/">Sign in locally</a>}</div>}
 {!data&&!loading&&<section className="welcome"><h1>What did you miss?</h1><p>Open a stock to understand what changed, what people are saying, and what it means. Your earlier thoughts stay here for next time.</p><p className="small muted">Real Yahoo Finance data. No sample companies or made-up answers.</p></section>}
 {loading&&<p role="status" className="muted">Getting prices, headlines and your saved research…</p>}
 {data&&<><section className="review-intro"><div className="stock-heading"><p className="eyebrow">{data.market.company} · {data.market.symbol} · {data.market.exchange}</p><Button variant="ghost" size="icon" aria-label="Refresh market data" onClick={()=>void openStock(data.market.symbol,true)} disabled={busy}><RefreshCw size={16}/></Button></div><h1>Here’s what you missed.</h1>
 <p className="review-summary"><strong className={data.market.changePercent>=0?'positive':'negative'}>{percent(data.market.changePercent)}</strong> across the last {data.market.closes.length-1} trading intervals. Latest observation: {data.market.closes.at(-1)!.close.toFixed(2)} {data.market.currency}.</p>{data.market.warnings.filter(w=>w.startsWith('Refresh failed')||w.startsWith('Price data is more')).map(w=><p key={w} role="status" className="notice">{w}</p>)}<p className="small muted">Price as of {date(data.market.priceAsOf)} · Retrieved {date(data.market.fetchedAt)}{data.cached?' · Cached data':''}</p>
 {latest?<div className="saved-catchup"><p className="answer-label">DEEPSEEK · SAVED {date(latest.createdAt)}</p><div onMouseUp={()=>{setExcerptOwner(latest.id);setSelectedExcerpt(window.getSelection()?.toString().trim()||'');}}><Answer analysis={latest}/></div><p className="small muted">Based on data retrieved {date(latest.market.fetchedAt)}. Refreshing prices does not rewrite this saved assessment.</p><Button variant="outline" onClick={()=>void ask('catchup')} disabled={busy||!configured}>{busy?'Investigating…':'Update catch-up'}</Button></div>:<div className="start-analysis"><p>{data.market.news.length?`${data.market.news.length} recent headlines are ready to review.`:'No matching headlines were returned. DeepSeek can discuss the price data, but may not be able to explain the move.'}</p><Button onClick={()=>void ask('catchup')} disabled={busy||!configured}>{busy?'Investigating…':'Catch me up'}</Button>{!configured&&<p className="small muted">Add your DeepSeek API key to enable analysis. You can already read sources and save notes.</p>}</div>}
 {latest?.research&&<details className="answer-detail"><summary>What this answer checked · {latest.research.sources.length} web sources</summary><Sources market={latest.market} research={latest.research}/></details>}
 <details className="answer-detail"><summary>Latest price & headline feed ({data.market.news.length})</summary><Sources market={data.market}/></details>
 <details className="answer-detail"><summary>What changed since last time?</summary>{previous.length?previous.map(a=><article className="history-note" key={a.id}><p className="answer-label">PREVIOUS ASSESSMENT · {date(a.createdAt)}</p><Answer analysis={a}/><details><summary className="small muted">Sources used then</summary><Sources market={a.market} research={a.research}/></details></article>):<p className="history-note small muted">{latest?'Your first catch-up is saved. The next new catch-up can compare against it.':'No previous analysis saved for this stock yet. Your first catch-up will establish a starting point.'}</p>}</details>
 <details className="analytics"><summary>Price comparison & limitations</summary><div className="price-table">{data.market.closes.map(p=><div key={p.date}><span>{new Date(p.date).toLocaleDateString()}</span><span>{p.close.toFixed(2)} {data.market.currency}</span></div>)}</div>{data.market.warnings.map(w=><p className="small muted" key={w}>{w}</p>)}</details>
 </section><div className="conversation-thread" aria-live="polite">{followups.map(a=><article className="conversation-turn" key={a.id}><div className="user-message">{a.question}</div><div className="assistant-message"><span className="answer-label">DEEPSEEK · {date(a.createdAt)}</span><div onMouseUp={()=>{setExcerptOwner(a.id);setSelectedExcerpt(window.getSelection()?.toString().trim()||'');}}><Answer analysis={a}/></div><details className="answer-detail"><summary>Sources used in this answer</summary><Sources market={a.market} research={a.research}/></details><button className="remember-button" onClick={()=>remember(`AI answer (${date(a.createdAt)}): ${(excerptOwner===a.id&&selectedExcerpt)||a.answer}`)}><Bookmark size={14}/>Save an excerpt</button></div></article>)}</div>
 <section className="ask-section">{latest?.research?.prepared.length?<div className="prepared-questions"><p className="small muted">Already explored for you · opens instantly</p>{latest.research.prepared.map(q=><details className="answer-detail" key={q.question}><summary>{q.question}</summary><Answer analysis={{...latest,answer:q.answer}}/><button className="remember-button" onClick={()=>remember(`Research (${date(latest.createdAt)}): ${q.answer}`)}><Bookmark size={14}/>Keep a thought from this</button></details>)}</div>:<div className="suggestions">{['What are people on Reddit worried about?', 'What might the headlines be missing?', 'What would change this explanation?'].map(q=><button key={q} disabled={busy||!configured} onClick={()=>void ask('question',q)}>{q}</button>)}</div>}
 <details className="answer-detail"><summary>What if I had chosen another stock?</summary><p className="small muted">Compare equal starting amounts on matching completed trading dates. This measures the outcome, not whether you could have known it then.</p><div className="comparison-inputs"><label>Alternative ticker<input aria-label="Alternative ticker" value={alternative} maxLength={20} placeholder="MSFT" onChange={e=>setAlternative(e.target.value.toUpperCase())}/></label><label>From date<input aria-label="Comparison start date" type="date" value={compareDate} onChange={e=>setCompareDate(e.target.value)}/></label><Button variant="outline" disabled={busy||!configured||!alternative||!compareDate} onClick={()=>void ask('question',`Compare ${data.market.symbol} with ${alternative} from ${compareDate} using matched adjusted prices. How would equal starting amounts have fared, and what does that outcome not tell me about decision quality?`)}>Compare</Button><button className="remember-button" disabled={!alternative||data.notes.length>=8} onClick={()=>remember(`I am considering ${alternative} as an alternative to ${data.market.symbol}. This is a thought, not a completed trade.`)}>Remember this alternative</button></div></details>
 <form className="composer" onSubmit={e=>{e.preventDefault();void ask('question');}}><label className="sr-only" htmlFor="question-input">Ask about {data.market.company}</label><Textarea id="question-input" value={question} maxLength={1500} onChange={e=>setQuestion(e.target.value)} placeholder={`Ask about ${data.market.company}…`} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey&&!e.nativeEvent.isComposing){e.preventDefault();e.currentTarget.form?.requestSubmit();}}}/><div className="composer-footer"><span>{data.market.symbol} · {busy?'Researching and weighing the evidence…':'Answers saved automatically'}</span><Button type="submit" size="icon" aria-label="Send question" disabled={busy||!configured||!question.trim()}><ArrowUp size={18}/></Button></div></form><p role="status" className="save-status">{status}</p><p className="prototype-note">AI can be wrong. Open the evidence to see what was read and what is still uncertain.</p></section>
 <details className="memory-section"><summary>Saved notes & export ({data.notes.length}/8)</summary><p className="small muted">Short notes you choose to include in future DeepSeek answers for this stock. They are your context, not verified evidence.</p>{data.notes.map(n=><div className="saved-note" key={n.id}><p>{n.text}<span className="small muted" style={{display:'block'}}>Saved {date(n.createdAt)}</span></p><button onClick={()=>void removeNote(n.id)}>Remove</button></div>)}<div className="memory-actions"><Button variant="outline" disabled={data.notes.length>=8} onClick={()=>remember()}><Bookmark size={14}/>Remember a thought</Button>{latest&&<Button variant="outline" disabled={data.notes.length>=8} onClick={()=>remember(`AI catch-up (${date(latest.createdAt)}): ${(excerptOwner===latest.id&&selectedExcerpt)||latest.answer}`)}>Save catch-up excerpt</Button>}<a href={`/api/research/export?symbol=${encodeURIComponent(data.market.symbol)}`} download><Download size={14}/>Export Markdown</a></div></details>
 </>}
 </main></SidebarInset>
 <Sheet open={noteOpen} onOpenChange={setNoteOpen}><SheetContent className="detail-sheet"><SheetHeader><SheetTitle>Remember for {data?.market.symbol}</SheetTitle><SheetDescription>Edit the excerpt to keep just what matters. This note will be sent to DeepSeek with future questions for this stock.</SheetDescription></SheetHeader><div className="sheet-body"><label htmlFor="saved-note">Your thought, alternative, or selected excerpt</label><Textarea id="saved-note" placeholder="I’m considering selling because… / I considered MSFT instead…" value={note} maxLength={600} onChange={e=>setNote(e.target.value)} className="reflection-input"/><p className="small muted">{note.length}/600 characters · up to eight notes per stock</p>{error&&<p role="alert">{error}</p>}<Button onClick={()=>void saveNote()} disabled={noteBusy||!note.trim()}>{noteBusy?'Saving…':'Save note'}</Button></div></SheetContent></Sheet>
 <Sheet open={info} onOpenChange={setInfo}><SheetContent className="detail-sheet"><SheetHeader><SheetTitle>Sources & setup</SheetTitle><SheetDescription>Real stock research, with explicit limits.</SheetDescription></SheetHeader><div className="sheet-body"><p>Yahoo Finance supplies recent daily prices and matching news headlines through unofficial endpoints. Availability is not guaranteed. Data may be delayed. Tavily retrieves article text and public Reddit thread text when accessible. Coverage is a limited sample, not a complete Reddit feed; extracted text can omit context and comments.</p><p>DeepSeek receives retrieved source text, your question, up to eight dated saved thoughts, the previous catch-up and two recent follow-ups. Analyses, their sources and notes are saved to your account’s local database.</p><p>{configured?'A DeepSeek key is configured. A successful answer confirms that it works.':'Set DEEPSEEK_API_KEY in the ignored .dev.vars file and restart the server. Keep the key on the server, not in chat or Git.'}</p><p>Market data is cached for 15 minutes. Unchanged catch-ups are reused for six hours. There is a limit of 30 model calls per account per UTC day, including failures. A research cycle uses up to three model calls and four Tavily searches. Prepared answers reopen without API calls. No background AI calls.</p><a href="/signin-with-chatgpt?return_to=/">Local sign-in</a></div></SheetContent></Sheet>
 </SidebarProvider>;
}
function Answer({analysis}:{analysis:SavedAnalysis}){
 const sources:Record<string,string>={P:analysis.market.source,...Object.fromEntries(analysis.market.news.map(n=>[n.id,n.url])),...Object.fromEntries((analysis.research?.sources??[]).map(n=>[n.id,n.url])),...Object.fromEntries((analysis.research?.comparisons??[]).map(n=>[n.id,n.alternativeSource]))};
 return <p className="generated-answer">{analysis.answer.split(/(\[(?:P|[NSC]\d+)\])/g).map((part,i)=>{const key=part.slice(1,-1);return /^\[(P|[NSC]\d+)\]$/.test(part)&&sources[key]?<a key={i} href={sources[key]} target="_blank" rel="noreferrer">{part}</a>:part;})}</p>;
}
function Sources({market,research}:{market:MarketSnapshot;research?:SavedAnalysis['research']}){return <div className="sources">{research&&<><p className="small muted">Investigated {date(research.searchedAt)}. Search and extracted text may be incomplete.</p>{research.gaps.map((gap,i)=><p className="small muted" key={i}>{gap}</p>)}{research.sources.map(source=><div className="source-record" key={source.id}><a href={source.url} target="_blank" rel="noreferrer">[{source.id}] {source.title}</a><p>{source.kind==='reddit'?'Public Reddit sample':'Web source'} · {source.coverage} · {source.publishedAt?date(source.publishedAt):'Publication date unavailable'} · Retrieved {date(source.retrievedAt)}</p><details><summary>Text available to the AI</summary><p className="small" style={{whiteSpace:'pre-wrap'}}>{source.text}</p></details></div>)}{research.comparisons.map(c=><div className="source-record" key={c.id}><p>[{c.id}] {c.start} to {c.end}: {c.symbol} {percent(c.returnPercent)} vs {c.alternative} {percent(c.alternativeReturnPercent)}. Difference: {c.differencePoints.toFixed(2)} percentage points.</p><p>{c.limitations}</p><a href={c.source} target="_blank" rel="noreferrer">{c.symbol} prices</a> · <a href={c.alternativeSource} target="_blank" rel="noreferrer">{c.alternative} prices</a></div>)}</>}<div className="source-record"><a href={market.source} target="_blank" rel="noreferrer">[P] Yahoo Finance price history</a><p>Price as of {date(market.priceAsOf)} · Retrieved {date(market.fetchedAt)}</p></div>{market.news.map(n=><div className="source-record" key={n.id}><a href={n.url} target="_blank" rel="noreferrer">[{n.id}] {n.title}</a><p>{n.publisher} · {date(n.publishedAt)} · Headline only</p></div>)}{!market.news.length&&<p className="small muted">No matching recent news returned. This does not establish that no news exists.</p>}</div>;}
